[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
actor = { path = "crates/actor" }
futures = "*"
supervisor = { path = "crates/supervisor" }
tokio = { version = "*", features = ["full"] }
mockall = "*"

[profile.dev]
debug = "limited"
